### ISSUE TITLE
spr.completed inconsistent firing times

### ISSUE THREAD

**Issue by Asynchronized** [Fraktality/spr#10]
Having issues with spr.completed() taking an insanely long time to fire, if at all, as in 10+ seconds. I tried playing around with the parameters and only got it to be consistent with a very high frequency number which doesn't exactly look super smooth for camera animation. I was watching the Camera's CFrame property while the animation was playing and noticed that the X axis of the CFrame's orientation was flickering anywhere from 0.036 to 0.038 before finally settling on 0.

```lua
--Cutscene Module
local CutsceneController = {}

local ReplicatedStorage = game:GetService('ReplicatedStorage')
local Spring = require(ReplicatedStorage:WaitForChild('spr'))
local Signal = require(ReplicatedStorage:WaitForChild('Signal'))
CutsceneController.CutsceneCompleted = Signal.new()

local Camera = game.Workspace.CurrentCamera

function CutsceneController:SetCameraTarget(Location : CFrame, Dampening : number, Frequency : number) : nil
  Camera.CameraType = Enum.CameraType.Scriptable
    
  Spring.completed(Camera,
    function()
      print('Cam move complete!')
      CutsceneController.CutsceneCompleted:Fire()
    end
  )
    
  Spring.target(
    Camera,
    Dampening,
    Frequency,
      {
        CFrame = Location
      }
    )
end
```

**Comment by fraktality** [comment]
This is due to numerical roundoff in the axis-angles->cframe and cframe->axis-angles conversions. This can be fixed by raising the angular sleep limit (which give snapping artifacts for large parts), or rewriting rotation conversions to use double precision. I'll implement the latter.

**Comment by Asynchronized** [comment]
Awesome, love it

**Comment by Asynchronized** [comment]
Having a new issue; Instead of the Z axis flickering for way too long, the CFrame values are now stuck unchanging for a long period of time and now won't fire the completed event at all

**Comment by objectionist** [comment]
bump. same thing @Asynchronized is dealing with

**Comment by fraktality** [comment]
Addressed by https://github.com/Fraktality/spr/pull/12
